server:
  port: 8080 # 指定后端服务启动的端口

spring:
  application:
    name: Campus-Lost-Found

  datasource:
    # 数据库连接地址 (注意时区我帮你补全为 Asia/Shanghai)
    url: jdbc:mysql://localhost:3306/campus_lost_found?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver # 告诉Spring Boot使用MySQL的驱动程序

  servlet:
    multipart:
      max-file-size: 10MB      # 单个文件最大允许 10MB
      max-request-size: 50MB   # 整个请求（可能包含多个文件）最大允许 50MB
    # 👇 新增邮件配置 👇
  mail:
    host: smtp.qq.com       # QQ邮箱的服务器地址 (如果是网易用 smtp.163.com)
    username: 3182055670@qq.com  # 替换成你的 QQ 邮箱
    password: sjlcbxgicjszdefd     # 替换成你获取到的“授权码”（绝不是QQ密码！）
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    # 开启驼峰命名自动映射（将数据库的 user_id 自动映射为 Java 里的 userId）
    map-underscore-to-camel-case: true